# see https://docs.zizmor.sh/audits/

rules:
  dependabot-cooldown:
    disable: true
  use-trusted-publishing:
    ignore:
      - build-publish.yml
  dangerous-triggers:
    ignore:
      - coverage.yml
