FROM python:3.11-slim

LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL description="ha-mqtt-discoverable test image"

RUN mkdir /config /data

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install --no-install-recommends -y apt-utils ca-certificates && \
    update-ca-certificates && \
    rm -fr /tmp/* /var/lib/apt/lists/* && \
    pip cache purge

# Keep from having to reinstall all the dependencies every time we
# rebuild
COPY requirements.txt /data
RUN pip install --no-cache-dir -r /data/requirements.txt

COPY dist/*.whl /data
RUN pip install --no-cache-dir /data/*.whl

# UID/GID 65534 are the standard nobody/nogroup IDs in Debian-based images.
USER 65534:65534

CMD ["bash", "-l"]
