FROM python:3.10

LABEL maintainer="Joe Block <jpb@unixorn.net>"
LABEL description="Test image for ha-mqtt-discoverable module"

RUN mkdir /data && \
  mkdir /config

RUN apt-get update && \
    apt-get install -y apt-utils ca-certificates --no-install-recommends && \
		update-ca-certificates && \
		rm -fr /tmp/* /var/lib/apt/lists/* && \
    pip cache purge

# Keep from having to reinstall all the dependencies every time we
# rebuild
COPY requirements.txt /data
RUN pip install --no-cache-dir -r /data/requirements.txt

COPY dist/*.whl /data
RUN pip install --no-cache-dir /data/*.whl

USER nobody

CMD ["bash", "-l"]
