#!/usr/bin/env bash
#
# Run black on all files in the repo

set -o pipefail

pydirs=()
for i in $(find . -iname '*.py' -exec dirname '{}' ';' | sort | uniq)
do
  pydirs+=($i)
done 

black "${pydirs[@]}"